### PR TITLE
Add rake and bundler tasks

### PR DESCRIPTION
**Pull request by techpeace**
I noticed this library hadn't been pushed to RubyGems quite yet, [so I took the liberty](https://rubygems.org/gems/frontapp) since I needed it for a project I'm working on.

This PR adds `rake` as a dependency, along with the necessary tasks to publish the gem. Let me know if you'd like me to transfer ownership of the gem over to you.

Thanks for the great lib!

### CODE REVIEW

**Comment by scarhand** [comment]
Thanks for the PR and for making the effort to publish it on RubyGems! It would be awesome if you could transfer ownership of the gem to me.

**Comment by FooBarWidget** [comment]
Hi @techpeace and thanks for the contribution. We wrote this gem mostly for internal purposes and didn't think others would find it useful, so it's good that you've found this gem valuable. Having said this, we neglected to put a license on this gem. Would you agree to apply the MIT license to your code contributions?

**Comment by techpeace** [comment]
Oh sorry about that @FooBarWidget, I neglected to check the license! Yes indeed, I agree to apply the MIT license to my contributions.

Sounds good @scarhand, I'll transfer it your way right now.

**Comment by techpeace** [comment]
@scarhand: Just realized I'll need the email address you'd like me to use for the new gem owner on RubyGems. Thanks!

**Comment by scarhand** [comment]
@techpeace oh yes, of course. Please use niels@pharynx.nl, thanks! As you might have noticed, I've also added the license.

**Comment by techpeace** [comment]
Apologies for the delay, @scarhand - transferred your way!

**Pull request merged**
