### PR TITLE
adds topics new endpoints

### PR DESCRIPTION
**Pull request by feolea**
👋  Adding some new topic endpoints available at [front](https://dev.frontapp.com/reference/topics-1)

### CODE REVIEW

**Comment by thatkaiguy** [comment]
maintainers - would appreciate a review when you get a moment!

**Comment by feolea** [comment]
@scarhand when you have a chance 🙏

**Comment by feolea** [comment]
Looks like Front have changed these days the api from topics to links, will have to update the PR !

**Comment by feolea** [comment]
Closing this one as Front have changed their `topics` endpoint to `links`

**Pull request closed without merging**
