### PR TITLE
Add api remove followers from a conversation

### PR DESCRIPTION
**Pull request by jefferal1995**
Add a new option to delete followers of a conversation.

Documentation
https://dev.frontapp.com/reference/delete_conversations-conversation-id-followers

@scarhand @thechrisoshow could you review it, please?

### CODE REVIEW

**Review by feolea — APPROVED** [review]
Looks good to me!

**Comment by jefferal1995-lending-home** [comment]
I added the api to add a follower in a conversation too.

**Review by feolea — APPROVED** [review]
even better! Thank you for that @jefferal1995 !

**Comment by feolea** [comment]
@scarhand can we get a review on this when you have a chance, please?

**Comment by scarhand** [comment]
Looks good to me! I'll push a new version.

**Pull request merged**
